# Generated by Django 6.0 on 2026-01-03 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('unit', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('norm_per_person', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Норматив на человека')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип услуги',
                'verbose_name_plural': 'Типы услуг',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('area', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Площадь (м²)')),
                ('residents_count', models.PositiveIntegerField(default=1, verbose_name='Количество проживающих')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата платежа')),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Потребление')),
                ('tariff', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Тариф')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('is_overpayment', models.BooleanField(default=False, verbose_name='Переплата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.apartment', verbose_name='Квартира')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.servicetype', verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.servicetype', verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
    ]
