# Generated by Django 6.0 on 2026-01-08 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserServiceNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm_per_person', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Норматив на человека')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.servicetype', verbose_name='Тип услуги')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользовательский норматив',
                'verbose_name_plural': 'Пользовательские нормативы',
                'unique_together': {('user', 'service_type')},
            },
        ),
    ]
